#!/usr/bin/python

import os, random, time
import update_info

def getForgeVersion():
  forge_version_file = "../src/net/minecraftforge/common/ForgeVersion.java"
  version = []
  for line in open(forge_version_file):
    if "=" in line:
      version.append(line.split("=")[1].strip(";\n").strip())
  return "Minecraft Forge " + ".".join(version)

def getMinecraftVersion():
  property_filename = "../src/fmlversion.properties"
  tofind = "fmlbuild.mcversion="
  for line in open(property_filename):
    if line.startswith(tofind):
      return line[len(tofind):].strip()
  return "unknown"

def run(cmd):
  print "> ", cmd
  exit_code = os.system(cmd)
  print "> Exit code = ", exit_code

def adfly(url):
  return "http://adf.ly/2137658/" + url

exp = os.path.expanduser

version = update_info.version
mcversion = getMinecraftVersion()
filename = "Factorization-{0}.jar".format(version, random.randrange(0, 1000))
oldfile = exp("~/Dropbox/Public/old/" + filename)
mfurl = exp("~/tmp/factorization_mediafire_url")
run("rm " + mfurl)
changelogFilename = "changelogs/Changelog-" + version + ".txt"
my_dropbox = "http://dl.dropbox.com/u/76265666/"

#Check for baddies
run("ack-grep NORELEASE src/")
run("ack-grep '%i' src/")

#Factorization
run("./make")
run("cp ~/Dropbox/dev/Factorization-dev.jar " + oldfile)
run("cp CHANGELOG ~/Dropbox/Public/old/")
run("cp CHANGELOG ~/Dropbox/Public/" + changelogFilename)
changelog_url = my_dropbox + changelogFilename

#Dropbox
dropbox_url = my_dropbox + "old/" + filename
run("dropbox_uploader.sh upload " + oldfile + " Public/old/" + filename)

#Mediafire
run("mediafire upload --quiet " + oldfile + " > " + mfurl)
mediafire_url = open(mfurl).read().strip().strip("()").strip()
if mediafire_url == "":
  print("Mediafire upload failed! Lameness! Enter the URL to use:")
  mediafire_url = raw_input()

#Don't add non-trivial tasks here unless we can get mediafire behaving properly.

print "\n"*4
LOG  = "Factorization " + version + " (MC " + mcversion + ")\n"
LOG += '''
[url="{0}"]adfly + MediaFire[/url], or\n[url="{1}"]adfly + DropBox[/url]
'''.format(
  adfly(mediafire_url),
  adfly(dropbox_url)
).strip() + "\n"
LOG += "Built on " + time.strftime("%F") + " against " + (getForgeVersion() + "\n")
LOG += '[url="{0}"]Changelog[/url]'.format(changelog_url)
print LOG
open("build.log", 'a').write(LOG+ '\n\n')

