#!/usr/bin/python

import os, random, time

def getForgeVersion():
  return "Minecraft Forge " + getMinecraftVersion()

def getMinecraftVersion():
  tofind = "fmlbuild.mcversion="
  for line in open("build.gradle"):
    if "FORGEMARK" in line:
      ret = line.split('"')[1].strip()
      return ret
  return "unknown"

def run(cmd):
  print "> ", cmd
  exit_code = os.system(cmd)
  print "> Exit code = ", exit_code

def adfly(url):
  return "http://adf.ly/2137658/" + url

def devify(name): return name.replace(".jar", "-dev.jar")

open("src/main/resources/assets/factorization/lang/en_US.lang").close()

exp = os.path.expanduser

run("./extract_license.py > src/main/resources/LICENSE.txt")

run("rm -f last_fz")
run("rm -f ~/tmp/factorization_last_commit")
run('git log | head -n 1 | line.py "_.split()[1]" > ~/tmp/factorization_last_commit')
commit = open(exp("~/tmp/factorization_last_commit")).read().strip()
run("rm -f ~/tmp/factorization_last_commit")

version = open("fzversion").read().strip()
mc_forge_version = getMinecraftVersion()
filename = "Factorization-{0}.jar".format(version)

run("./rungradle build deobfJar writeFzFile")

oldfile = exp("~/Dropbox/Public/old/" + filename)
last_fz = open("last_fz").read().strip()
run("cp " + last_fz + " " + oldfile)
run("cp " + devify(last_fz) + " " + devify(oldfile))
mfurl = exp("~/tmp/factorization_mediafire_url")
run("rm " + mfurl)
changelogFilename = "changelogs/Changelog-" + version + ".txt"
my_dropbox = "http://dl.dropbox.com/u/76265666/"

#Check for baddies
run("./check_norelease")

#Factorization
run("cp CHANGELOG ~/Dropbox/Public/old/")
run("cp CHANGELOG ~/Dropbox/Public/" + changelogFilename)
changelog_url = my_dropbox + changelogFilename

#Dropbox
dropbox_url = my_dropbox + "old/" + filename
run("dropbox_uploader.sh upload " + oldfile + " Public/old/" + filename)
run("dropbox_uploader.sh upload " + devify(oldfile) + " Public/old/" + devify(filename))

#Mediafire
run("mediafire upload --quiet " + oldfile + " > " + mfurl)
mediafire_url = open(mfurl).read().strip().strip("()").strip()
if mediafire_url == "":
  print("Mediafire upload failed! Lameness! Enter the URL to use:")
  mediafire_url = raw_input()

#Don't add non-trivial tasks here unless we can get mediafire behaving properly.

print("\n"*4)
LOG  = "Factorization " + version + "\n"
LOG += '''
[url="{0}"]adfly + MediaFire[/url], or\n[url="{1}"]adfly + DropBox[/url]
'''.format(
  adfly(mediafire_url),
  adfly(dropbox_url)
).strip() + "\n"
LOG += "Built on " + time.strftime("%F") + " against " + (getForgeVersion() + "\n")
LOG += '[url="{0}"]Changelog[/url]\n'.format(changelog_url)
LOG += '[url="{0}"]Deobf for Mod Authors[/url]\n'.format(devify(dropbox_url))
LOG += '' + commit
print(LOG)
print
print "Update targets:"
for _ in "IRC topic; twitter; patreon; forum thread; forgecraft".split('; '):
    print "[ ]", _

open("build.log", 'a').write(LOG+ '\n\n')

db = os.system("pidof dropbox > /dev/zero")
if db:
    print()
    print()
    print("Dropbox not running! Starting dropbox")
    os.system("dropbox &")
