#!/usr/bin/python

import os, random, time
import update_info

def getForgeVersion():
  forge_version_file = "../forge/mcp/src/minecraft/net/minecraftforge/common/ForgeVersion.java"
  version = []
  for line in open(forge_version_file):
    if "=" in line:
      version.append(line.split("=")[1].strip(";\n").strip())
  return "Minecraft Forge " + ".".join(version)


def run(cmd):
  print "> ", cmd
  exit_code = os.system(cmd)
  print "> Exit code = ", exit_code

def adfly(url):
  return "http://adf.ly/2137658/" + url

exp = os.path.expanduser

version = update_info.version
filename = "Factorization-{0}.jar".format(version, random.randrange(0, 1000))
oldfile = exp("~/Dropbox/Public/old/" + filename)
mfurl = exp("~/tmp/factorization_mediafire_url")
run("rm " + mfurl)

#Check for baddies
run("ack-grep NORELEASE src/")

#Factorization
run("./make")
run("cp ~/Dropbox/dev/Factorization-dev.jar " + oldfile)

#Dropbox
dropbox_url = "dl.dropbox.com/u/76265666/old/" + filename
run("dropbox_uploader.sh upload " + oldfile + " Public/old/" + filename)

#Mediafire
run("mediafire upload --quiet " + oldfile + " > " + mfurl)
mediafire_url = open(mfurl).read().strip().strip("()").strip()

print "\n"*4
LOG  = "Factorization " + version + " (MC 1.5.1)\n"
LOG += '''
[url="{0}"]adfly + MediaFire[/url], or\n[url="{1}"]adfly + DropBox[/url]
'''.format(
  adfly(mediafire_url),
  adfly(dropbox_url)
).strip() + "\n"
LOG += "Built on " + time.strftime("%F") + " against " + (getForgeVersion() + "\n")
print LOG
open("build.log", 'a').write(LOG+ '\n\n')

