#!/bin/sh

if git branch | grep "*" | grep fzds > /dev/zero;
then
    EXCLUDE="--ignore-dir=src/factorization/fzds/"
else
    EXCLUDE=""
fi

ack-grep $EXCLUDE NORELEASE src/ QUICK_BUGS TODO
ack-grep '%i' src/
