#!/bin/bash
#set -e

BASE=$(dirname `pwd`/$0)/
cd $BASE/../

#Now in FZ/forge shared directory
cd forge/mcp
#Now in forge/mcp

mkdir -p src/minecraft/factorization/
pushd src/minecraft/factorization
  ln -s $BASE/src/common/* ./
popd

pushd src/minecraft/
  ln -s $BASE/APIS/* ./
popd

pushd lib/
  ln -s $BASE/resources/mods/
popd

mkdir -p jars/saves
pushd jars/saves
  unzip $BASE/testworld.zip
popd
