#!/bin/bash
set -e

BASE=$(dirname `pwd`/$0)/
cd $BASE/../

#Now in FZ/forge shared directory
cd forge/mcp
#Now in forge/mcp

mkdir -p src/minecraft/factorization/
pushd src/minecraft/factorization
  ln -s $BASE/src/common/* ./
popd

mkdir -p lib/factorization
pushd lib/factorization
  ln -s $BASE/texture/
popd

mkdir -p jars/saves
pushd jars/saves
  unzip $BASE/testworld.zip
popd
