#!/bin/sh

set -e


echo Replace $NEEDLE with $REPLACE

HAY=$(find src/main/resources/assets/factorization/ | grep mtl$)
for filename in $HAY; do
    echo "Processing:" $filename
    rm -rf .tmp
    #map_Kd /home/poseidon/Development/FzGradle/factorization/resources/assets/factorization/textures/blocks/resource/dark_iron_block
    #map_Kd factorization:blocks/resource/dark_iron_block

    cat $filename \
       | sed -r "s/map_Kd \/.*\/([^/]+)\/textures\//map_Kd \1:/g" \
       | sed "s/\.png//g" > .tmp
    cat .tmp > $filename
    rm -rf .tmp
done
