#!/bin/bash

set -e

./build_core_mod

cd ../

pushd ~/mc > /dev/zero
  ./install dev
popd > /dev/zero

echo Packaging client
pushd reobf/minecraft  > /dev/zero
  cp -R ../../factorization/texture/ factorization/texture/
  cp ../../factorization/*.info ./
  rm -rf factorization/texture/ignore/
  jar -cf ~/Dropbox/dev/Factorization-dev.jar *Factorization*.class *.info factorization/
popd > /dev/zero
pushd ~/mc/
  ./install test
popd
cp ~/Dropbox/dev/Factorization-dev.jar ~/.minecraft/mods/Factorization.jar

#echo Packaging server
#pushd reobf/minecraft_server > /dev/zero
#  jar -cf ~/Dropbox/dev/Factorization_server-dev.jar *Factorization*.class factorization/
#popd > /dev/zero


