#!/bin/bash

set -e

echo Packaging client
./update_info.py
#./build_core_mod

FZ=`pwd`
OUT=~/Dropbox/dev/Factorization-dev.jar

pushd ../forge/mcp/reobf/minecraft  > /dev/zero
  cp -R $FZ/texture/mods ./
  cp $FZ/*.info ./
  cp $FZ/CHANGELOG ./
  rm $OUT
  jar -cf $OUT CHANGELOG *.info factorization/ ./mods
  #jar -cf ~/Dropbox/dev/$OUT *Factorization*.class *.info factorization/
popd > /dev/zero
#pushd ~/mc/
#  ./install modded-1.3
#popd
#cp ~/Dropbox/dev/Factorization-dev.jar ~/.minecraft/mods/

#echo Packaging server
#pushd reobf/minecraft_server > /dev/zero
#  jar -cf ~/Dropbox/dev/Factorization_server-dev.jar *Factorization*.class factorization/
#popd > /dev/zero


