#!/bin/bash

#mv ../forge/mcp/eclipse ../
pushd ../forge/
  python install.py
popd
./embed_source
echo "Remember to set the lib/ classpath in eclipse!"

#rm -r ../forge/mcp/eclipse
#ln -s `pwd`/../eclipse ../forge/mcp
#mv ../eclipse ../forge/mcp/

