#!/bin/bash

git submodule update

FORGE_AT=src/main/resources/forge_at.cfg
git checkout $FORGE_AT
cat ../factorization/src/main/resources/*.cfg > $FORGE_AT

./gradlew clean
./gradlew setupForge
./gradlew eclipse

